# Generated by Django 2.2.2 on 2019-06-28 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='start_time',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='event_time',
            field=models.CharField(default='00:00-00:00', max_length=50),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='lang',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='fee',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='flyer',
            field=models.ImageField(upload_to='myapp', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='registration',
            field=models.CharField(default='Not required', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='venue',
            field=models.CharField(default='Place@url', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(upload_to='myapp', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
