# Generated by Django 2.2.2 on 2019-06-28 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190628_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='flyer',
            field=models.FileField(upload_to='myapp', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
