# Generated by Django 2.2.2 on 2019-06-28 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190628_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='flyer',
            field=models.FileField(upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(upload_to='thumbnail', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
